// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatistikkApp.Data;

#nullable disable

namespace StatistikkApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("StatistikkApp.Models.Kommune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KommuneNummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kommuner");
                });

            modelBuilder.Entity("StatistikkApp.Models.StatistikkData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KommuneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatistikkKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Verdi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KommuneId");

                    b.HasIndex("StatistikkKategoriId");

                    b.ToTable("StatistikkData");
                });

            modelBuilder.Entity("StatistikkApp.Models.StatistikkKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatistikkKategorier");
                });

            modelBuilder.Entity("StatistikkApp.Models.StatistikkData", b =>
                {
                    b.HasOne("StatistikkApp.Models.Kommune", "Kommune")
                        .WithMany("StatistikkData")
                        .HasForeignKey("KommuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatistikkApp.Models.StatistikkKategori", "StatistikkKategori")
                        .WithMany("StatistikkData")
                        .HasForeignKey("StatistikkKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kommune");

                    b.Navigation("StatistikkKategori");
                });

            modelBuilder.Entity("StatistikkApp.Models.Kommune", b =>
                {
                    b.Navigation("StatistikkData");
                });

            modelBuilder.Entity("StatistikkApp.Models.StatistikkKategori", b =>
                {
                    b.Navigation("StatistikkData");
                });
#pragma warning restore 612, 618
        }
    }
}
